/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "platform_Types.h"
//RCC
#define RCC_BASE         0x40021000
#define RCC_APB2ENR     *(volatile uint32_t *) (RCC_BASE + 0x18)
#define RCC_IOPCEN      4
#define RCC_IOPAEN      2
#define RCC_AFIO        0

//GPIOC
#define GPIOC_BASE       0x40011000
#define GPIOC_CRH       *(volatile uint32_t *) (GPIOC_BASE + 0x04)
#define GPIOC_ODR       *(volatile uint32_t *) (GPIOC_BASE + 0x0C)
//GPIOA
#define GPIOA_BASE       0x40010800
#define GPIOA_CRL       *(volatile uint32_t *) (GPIOA_BASE + 0x00)
//AFIO
#define AFIO_BASE       0x40010000
#define AFIO_EXTICR1    *(volatile uint32_t *) (AFIO_BASE + 0x08)

//EXTI
#define EXTI_BASE   0x40010400
#define EXTI_IMR    *(volatile uint32_t *) (EXTI_BASE + 0x00)
#define MR0         0
#define EXTI_RTSR   *(volatile uint32_t *) (EXTI_BASE + 0x08)
#define TR0         0
#define EXTI_PR     *(volatile uint32_t *) (EXTI_BASE + 0x14)
#define PR0         0

//NVIC
#define NVIC          0xE000E100
#define NVIC_ISER0    *(volatile uint32_t *) (NVIC + 0x00)

//Macros
#define SET_BIT(Regiter,bit)     (Regiter|= (1UL<<bit))
#define RESET_BIT(Regiter,bit)     (Regiter&= ~(1UL<<bit))
#define RESET_HBYTE(Regiter,S_bit)     (Regiter &= ~(0x0F<<S_bit))

typedef union{
	vuint32    PORT;
	struct{
		vuint32	  P_0:1;
		vuint32	  P_1:1;
		vuint32	  P_2:1;
		vuint32	  P_3:1;
		vuint32	  P_4:1;
		vuint32	  P_5:1;
		vuint32	  P_6:1;
		vuint32	  P_7:1;
		vuint32	  P_8:1;
		vuint32	  P_9:1;
		vuint32	  P_10:1;
		vuint32	  P_11:1;
		vuint32	  P_12:1;
		vuint32	  P_13:1;
	}PIN;

}R_16bit_t;

volatile R_16bit_t* R_ODR = (volatile R_16bit_t*) (GPIOC_BASE + 0x0C);

void init_RCC(){
	SET_BIT(RCC_APB2ENR,RCC_IOPCEN);
	//RCC_APB2ENR |=(1<<RCC_IOPAEN);
	SET_BIT(RCC_APB2ENR,RCC_IOPAEN);
	SET_BIT(RCC_APB2ENR,RCC_AFIO);
}
void init_GPIO(){
	RESET_HBYTE(GPIOC_CRH,20);
	//GPIOC_CRH &= 0xFF0FFFFF;
	SET_BIT(GPIOC_CRH,21);
	//GPIOC_CRH |= 0x00200000;
	//In input mode (MODE[1:0]=00):
	//01: Floating input (reset state)
	SET_BIT(GPIOA_CRL,2);
}
void init_EXTI(){
	SET_BIT(NVIC_ISER0,6);
	//EXTI0[3:0]: EXTI0
	//0000: PA0 pin
	RESET_HBYTE(AFIO_EXTICR1,0);
	SET_BIT(EXTI_IMR,MR0);
	SET_BIT(EXTI_RTSR,TR0);
}
int main(void)
{
	init_RCC();
	init_GPIO();
	init_EXTI();
	while(1);
}
void EXTI0_IRQHandler(){
	(R_ODR->PIN.P_13) ^= 1;
	SET_BIT(EXTI_PR,PR0);
}
